### PR TITLE
Remove Bandit and Ruff PL rule

### PR DESCRIPTION
**Pull request by smk4664**
This removes Bandit from the cookie and removes the Ruff PL rule as Pylint is still going to be done seperately.

### CODE REVIEW

**Comment by gsnider2195** [comment]
All `nosec` comments need to be removed:

```
nautobot-app-chatops/{{ cookiecutter.project_slug }}/development/mattermost/nautobot_bootstrap.py:29:    "clear": "u7p1an973bd1jqg75i3y7pxj7y",  # nosec
nautobot-app-chatops/{{ cookiecutter.project_slug }}/development/mattermost/nautobot_bootstrap.py:30:    "nautobot": "ncygprhkt3rrxr4rkytcaa7c9c",  # nosec
nautobot-app-chatops/{{ cookiecutter.project_slug }}/development/mattermost/nautobot_bootstrap.py:31:    "{{ cookiecutter.chatops_interactive_command }}": "fh1kbk45xtgm8r48jzr39ru1ww",  # nosec
```

**Comment by gsnider2195** [comment]
Please remove these also

```
development/Dockerfile.dockerignore:4:!/.bandit.yml
docs/dev/dev_environment.md:105:  bandit           Run bandit to validate basic static code security analysis.
docs/dev/dev_environment.md:307:➜ invoke bandit
nautobot-app-chatops/{{ cookiecutter.project_slug }}/pyproject.toml:41:bandit = "*"
nautobot-app-chatops/{{ cookiecutter.project_slug }}/pyproject.toml:105:    "S",  # bandit
nautobot-app-ssot/{{ cookiecutter.project_slug }}/pyproject.toml:38:bandit = "*"
nautobot-app-ssot/{{ cookiecutter.project_slug }}/pyproject.toml:102:    "S",  # bandit
nautobot-app/{{ cookiecutter.project_slug }}/pyproject.toml:101:    "S",  # bandit
poetry.lock:37:name = "bandit"
poetry.lock:43:    {file = "bandit-1.7.5-py3-none-any.whl", hash = "sha256:75665181dc1e0096369112541a056c59d1c5f66f9bb74a8d686c3c362b83f549"},
poetry.lock:44:    {file = "bandit-1.7.5.tar.gz", hash = "sha256:bdfc739baa03b880c2d15d0431b31c658ffc348e907fe197e54e0389dd59e11e"},
pyproject.toml:19:bandit = "*"
pyproject.toml:70:    "S",  # bandit
```

**Comment by gsnider2195** [comment]
Bandit config files need to be removed

```
./.bandit.yml
./nautobot-app-chatops/{{ cookiecutter.project_slug }}/.bandit.yml
./nautobot-app-ssot/{{ cookiecutter.project_slug }}/.bandit.yml
./nautobot-app/{{ cookiecutter.project_slug }}/.bandit.yml
```

**Comment by smk4664** [comment]
Ah, I thought the symlinks removed automatically. It didn't show up in a local search.

**Comment by smk4664** [comment]
> Please remove these also
> 
> ```
> development/Dockerfile.dockerignore:4:!/.bandit.yml
> docs/dev/dev_environment.md:105:  bandit           Run bandit to validate basic static code security analysis.
> docs/dev/dev_environment.md:307:➜ invoke bandit
> nautobot-app-chatops/{{ cookiecutter.project_slug }}/pyproject.toml:41:bandit = "*"
> nautobot-app-chatops/{{ cookiecutter.project_slug }}/pyproject.toml:105:    "S",  # bandit
> nautobot-app-ssot/{{ cookiecutter.project_slug }}/pyproject.toml:38:bandit = "*"
> nautobot-app-ssot/{{ cookiecutter.project_slug }}/pyproject.toml:102:    "S",  # bandit
> nautobot-app/{{ cookiecutter.project_slug }}/pyproject.toml:101:    "S",  # bandit
> poetry.lock:37:name = "bandit"
> poetry.lock:43:    {file = "bandit-1.7.5-py3-none-any.whl", hash = "sha256:75665181dc1e0096369112541a056c59d1c5f66f9bb74a8d686c3c362b83f549"},
> poetry.lock:44:    {file = "bandit-1.7.5.tar.gz", hash = "sha256:bdfc739baa03b880c2d15d0431b31c658ffc348e907fe197e54e0389dd59e11e"},
> pyproject.toml:19:bandit = "*"
> pyproject.toml:70:    "S",  # bandit
> ```

Some of these, such as the pyproject.toml are the Ruff Bandit rules, which we do want.

**Review by gsnider2195 — APPROVED** [review]

**Pull request merged**
